name    'andschwa-ubuntu'
version '0.0.2'
source 'git://github.com/andschwa/puppet-ubuntu.git'
author 'Andrew Schwartzmeyer'
license 'MIT License'
summary 'Manage Ubuntu repositories'
description 'Defines repositories for my Ubuntu servers'
project_page 'https://github.com/andschwa/puppet-ubuntu'

dependency 'puppetlabs/apt', '>= 1.4.0'
dependency 'puppetlabs/stdlib', '>=  4.1.0'
